const ibmdb = require('../db')
const log = require('../../log')

module.exports = {
    findServiciosByRepresentanteLegalAndEmpresaAndTipoServicioList: (rut_empresa, rut_representante, lstTiposServicios) => {
        return ibmdb.query('SELECT pNatural.RUT AS "RUT_REPRESENTANTE", pJuridica.RUT AS "RUT_RESPONSABLE", s.IDENT_SERVICIO AS "FOLIO", s.CODIGO_REGION AS "REGION" ' +
        'FROM NULLID.RNT_TIPO_SERVICIO ts INNER JOIN NULLID.RNT_SERVICIO s ON s.ID_TIPO_SERVICIO = ts.ID ' +
        'INNER JOIN NULLID.RNT_RESPONSABLE_SERVICIO rs ON s.ID_RESPONSABLE_SERVICIO = rs.ID ' +
        'INNER JOIN NULLID.RNT_PERSONA pJuridica ON pJuridica.id = rs.ID_PERSONA AND PJURIDICA.TIPO_PERSONA = 2 ' +
        'INNER JOIN NULLID.RNT_SERVICIO_REPRESENTANTE sr ON sr.ID_SERVICIO = s.ID ' +
        'INNER JOIN NULLID.RNT_PERSONA pNatural ON PNATURAL.id = sr.ID_REPRESENTANTE_SERVICIO AND pNatural.TIPO_PERSONA = 1 ' +
        'WHERE PJURIDICA.RUT = ? AND PNATURAL.RUT = ? AND s.ACTIVO = 1 AND ts.id in (' + lstTiposServicios.toString() + ')', [rut_empresa, rut_representante])
    },
    findRecorridosByFolioRegionAndTipoServicio: (folio,region, lstTipoServicios) => {
        return ibmdb.query('SELECT rec.NOMBRE AS "NOMBRE_RECORRIDO" ' + 
        'FROM NULLID.RNT_SERVICIO s INNER JOIN NULLID.RNT_RECORRIDO rec ON s.id = rec.ID_SERVICIO ' +
        'INNER JOIN NULLID.RNT_TIPO_SERVICIO ts ON s.ID_TIPO_SERVICIO = ts.ID ' +
        'WHERE s.IDENT_SERVICIO = ? AND s.CODIGO_REGION = ? AND s.ACTIVO = 1 AND rec.ESTADO = 1 AND ts.id IN (' + lstTipoServicios.toString() +')',[folio,region])
    },
    findServiciosByMandatarioAndRepresentanteAndEmpresaAndTiposServicios: (rut_empresa, rut_representante, rut_solicitante, lstTipoServicios) => {
        return ibmdb.query('SELECT pNatural.RUT AS "RUT_REPRESENTANTE", pJuridica.RUT AS "RUT_RESPONSABLE", MANDATARIOPERSONA.RUT AS "RUT_MANDATARIO", s.IDENT_SERVICIO AS "FOLIO", s.CODIGO_REGION AS "REGION" ' +
        'FROM NULLID.RNT_TIPO_SERVICIO ts INNER JOIN NULLID.RNT_SERVICIO s ON s.ID_TIPO_SERVICIO = ts.ID ' +
        'INNER JOIN NULLID.RNT_RESPONSABLE_SERVICIO rs ON s.ID_RESPONSABLE_SERVICIO = rs.ID ' +
        'INNER JOIN NULLID.RNT_PERSONA pJuridica ON pJuridica.id = rs.ID_PERSONA AND PJURIDICA.TIPO_PERSONA = 2 ' +
        'INNER JOIN NULLID.RNT_SERVICIO_REPRESENTANTE sr ON sr.ID_SERVICIO = s.ID ' +
        'INNER JOIN nullid.RNT_REPRESENTATE_LEGAL rl ON rl.id = sr.ID_REPRESENTANTE_SERVICIO ' +
        'INNER JOIN NULLID.RNT_PERSONA pNatural ON PNATURAL.id = sr.ID_REPRESENTANTE_SERVICIO AND pNatural.TIPO_PERSONA = 1 ' +
        'INNER JOIN NULLID.RNT_REPRESENTANTE_LEGAL_MANDATARIO rlm ON rlm.ID_REPRESENTANTE_LEGAL = rl.ID ' +
        'INNER JOIN NULLID.RNT_MANDATARIO man ON man.id = rlm.ID_MANDATARIO ' + 
        'INNER JOIN nullid.RNT_PERSONA mandatarioPersona ON MANDATARIOPERSONA.id = man.ID_PERSONA ' +
        'LEFT JOIN NULLID.RNT_MODALIDAD ON RNT_MODALIDAD.ID = RNT_TIPO_SERVICIO.ID_MODALIDAD ' +
        'LEFT JOIN NULLID.RNT_CATEGORIA_TRANSPORTE ON RNT_CATEGORIA_TRANSPORTE.ID = RNT_TIPO_SERVICIO.ID_CATEGORIA_TRANSPORTE ' +
        'LEFT JOIN NULLID.RNT_MEDIO_TRANSPORTE ON RNT_MEDIO_TRANSPORTE.ID = RNT_TIPO_SERVICIO.ID_MEDIO_TRANSPORTE ' +
        'LEFT JOIN NULLID.RNT_TIPO_TRANSPORTE ON RNT_TIPO_TRANSPORTE.ID = RNT_TIPO_SERVICIO.ID_TIPO_TRANSPORTE ' +
        'LEFT JOIN NULLID.RNT_TIPO_VEHICULO_SERVICIO ON RNT_TIPO_VEHICULO_SERVICIO.ID = RNT_TIPO_SERVICIO.ID_TIPO_VEHICULO_SERVICIO ' +
        'LEFT JOIN NULLID.RNT_TIPO_SERVICIO_AREA ON RNT_TIPO_SERVICIO.ID_tipo_servicio_area = RNT_TIPO_SERVICIO_AREA.ID ' +
        'WHERE PJURIDICA.RUT = ? AND PNATURAL.RUT = ? AND MANDATARIOPERSONA.RUT = ? AND s.ACTIVO = 1 AND ts.id in (' + lstTipoServicios.toString() + ')', [rut_empresa, rut_representante, rut_solicitante])
    },
    getServiciosVigentesInscritosPorRutResponsable: (rut_responsable,lstTipoServicios) =>{
        return ibmdb.query("SELECT REGION.ID ID_REGION, REGION.NOMBRE REGION, T_VEHICULO_SERV.NOMBRE || ' ' || MODALIDAD.NOMBRE || ' ' || T_SERV_AREA.NOMBRE, VISTA.IDENT_SERVICIO FOLIO, PERSONA.NOMBRE " +
        "FROM NULLID.RNT_SERVICIO AS VISTA " +
		"INNER JOIN NULLID.RNT_TIPO_SERVICIO AS T_SERV ON T_SERV.ID = VISTA.ID_TIPO_SERVICIO " +
		"INNER JOIN NULLID.RNT_SERVICIO_REPRESENTANTE SR ON VISTA.ID = SR.ID_SERVICIO " +
		"INNER JOIN NULLID.RNT_REPRESENTATE_LEGAL AS RL ON SR.ID_REPRESENTANTE_SERVICIO = RL.ID " +
		"INNER JOIN NULLID.RNT_PERSONA AS PERSONA ON PERSONA.ID = RL.ID_PERSONA " +
		"LEFT JOIN NULLID.RNT_MODALIDAD AS MODALIDAD ON MODALIDAD.ID = T_SERV.ID_MODALIDAD " +
		"LEFT JOIN NULLID.RNT_TIPO_VEHICULO_SERVICIO AS T_VEHICULO_SERV ON T_VEHICULO_SERV.ID = T_SERV.ID_TIPO_VEHICULO_SERVICIO " +
		"LEFT JOIN NULLID.RNT_TIPO_CONTRATO AS TIPO_CONTRATO ON TIPO_CONTRATO.ID = VISTA.ID_TIPO_CONTRATO " +
		"LEFT JOIN NULLID.RNT_TIPO_REPRESENTANTE TR ON TR.ID = RL.ID_TIPO_REPRESENTANTE_LEGAL " +
		"LEFT JOIN NULLID.RNT_TIPO_SERVICIO_AREA AS T_SERV_AREA ON T_SERV.ID_TIPO_SERVICIO_AREA = T_SERV_AREA.ID " +
		"LEFT JOIN NULLID.RNT_CATEGORIA_TRANSPORTE AS CATEGORIA_TRANS ON CATEGORIA_TRANS.ID = T_SERV.ID_CATEGORIA_TRANSPORTE " +
        "LEFT JOIN NULLID.UTILSQA_REGION AS REGION ON REGION.ID = VISTA.CODIGO_REGION " +
        "WHERE PERSONA.RUT = ? AND T_SERV.ID IN (" + lstTipoServicios.toString() + ")",[rut_responsable])
    }
}