const koa = require('koa') 
const Router = require('koa-router')
const busesRoute = require('./routes/buses')
const colectivosRoute = require('./routes/colectivos')
const escolarRoute = require('./routes/escolar')
const privadoRoute = require('./routes/privado')
const taxisRoute = require('./routes/taxis')
const logger = require('./log')
const port = 3000
const app = new koa()
const router = new Router()
router.use('/buses',busesRoute)
router.use('/taxis_colectivos',colectivosRoute)
router.use('/escolares',escolarRoute)
router.use('/privados',privadoRoute)
router.use('/taxis',taxisRoute)
app.use(router.routes())
app.listen(port, () => {
    logger.debug("RNT-API iniciado en puerto: " + port)
    // console.log("RNT-API iniciado en puerto: " + port)
})