/* generated by wsdl2js.py (http://www.bolinfest.com/wsdl2js/) */

function Obj() {
   /*string*/ this["nombreSub"] = null;
   /*string*/ this["detalle"] = null;
   /*boolean*/ this["empty"] = null;
}

function PlacaObj() {
   /*string*/ this["aaFabric"] = null;
   /*string*/ this["cancelacion"] = null;
   /*string*/ this["chasis"] = null;
   /*string*/ this["cid"] = null;
   /*string*/ this["color"] = null;
   /*string*/ this["encargo"] = null;
   /*LimitaObj*/ this["limita"] = null;
   /*string*/ this["marca"] = null;
   /*string*/ this["modelo"] = null;
   /*string*/ this["motor"] = null;
   /*string*/ this["patente"] = null;
   /*PropieAanterObj*/ this["propieAanter"] = null;
   /*PropieActualObj*/ this["propieActual"] = null;
   /*string*/ this["seguro"] = null;
   /*string*/ this["serie"] = null;
   /*SubinscObj*/ this["subinsc"] = null;
   /*string*/ this["tipoCombust"] = null;
   /*string*/ this["tipoVehi"] = null;
   /*string*/ this["valPBV"] = null;
   /*string*/ this["vin"] = null;
}

function PPUServiceIOExceptionObj() {
   /*Obj*/ this["parameters"] = null;
}

function getPlacaResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function PPUServiceMalformedURLExceptionObj() {
   /*Obj*/ this["parameters"] = null;
}

function PropieAanterObj() {
   /*Obj*/ this["itemPropieaanter"] = null;
   /*Obj*/ this["propant"] = null;
   /*Obj*/ this["itemPropant"] = null;
   /*string*/ this["nombres"] = null;
   /*string*/ this["rut"] = null;
   /*string*/ this["oficina"] = null;
   /*string*/ this["nro"] = null;
   /*string*/ this["fecha"] = null;
   /*boolean*/ this["empty"] = null;
}

function SubinscObj() {
   /*Obj*/ this["itemSubinsc"] = null;
   /*string*/ this["nombreSub"] = null;
   /*string*/ this["detalle"] = null;
   /*boolean*/ this["empty"] = null;
}

function MalformedURLExceptionObj() {
  // no properties listed, wsdl2js failed for this type
}

function PropieActualObj() {
   /*string*/ this["fecAquis"] = null;
   /*string*/ this["fecha"] = null;
   /*string*/ this["nro"] = null;
   /*string*/ this["oficina"] = null;
   /*PropactObj*/ this["propact"] = null;
}

function IOExceptionObj() {
  // no properties listed, wsdl2js failed for this type
}

function LimitaObj() {
   /*Obj*/ this["itemLimita"] = null;
   /*string*/ this["titulo"] = null;
   /*string*/ this["documento"] = null;
   /*string*/ this["naturaleza"] = null;
   /*string*/ this["comuna"] = null;
   /*string*/ this["causa"] = null;
   /*string*/ this["ACausa"] = null;
   /*string*/ this["fechaDoc"] = null;
   /*string*/ this["autorizante"] = null;
   /*string*/ this["acreedor"] = null;
   /*string*/ this["repertorio"] = null;
   /*string*/ this["numReper"] = null;
   /*string*/ this["fecReper"] = null;
   /*boolean*/ this["empty"] = null;
   /*Obj*/ this["tenedores"] = null;
   /*Obj*/ this["itemTenedores"] = null;
   /*string*/ this["nombres"] = null;
   /*string*/ this["rut"] = null;
   /*boolean*/ this["empty"] = null;
}

function PropactObj() {
   /*Obj*/ this["itemPropact"] = null;
   /*string*/ this["nombres"] = null;
   /*string*/ this["rut"] = null;
   /*string*/ this["calle"] = null;
   /*string*/ this["nro"] = null;
   /*string*/ this["restdom"] = null;
   /*string*/ this["comuna"] = null;
}

function getPlacaRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

/**
 * @param getPlacaRequest of type getPlacaRequestObj
 * @return getPlacaResponse
 */
function getPlaca(getPlacaRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "http://ws.mtt.cl/services/PPUService_API_Tramites.PPUService_API_TramitesHttpSoap11Endpoint";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getPlacaRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getPlaca", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getPlacaResponseObj();
    var node0 = (translation.body.getElementsByTagName('getPlacaResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('nombreSub')[0].firstChild;
      obj1['nombreSub'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('detalle')[0].firstChild;
      obj1['detalle'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('empty')[0].firstChild;
      obj1['empty'] = (temp == null) ? null : (temp.nodeValue == 'true');
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

